apiVersion: v1
data:
  RELATED_IMAGE_BACKFILL_REDIS: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9@sha256:bf0187757bb063f03e9a02f352a5cb6545263f844098b3ba91901224c7e08cae
  RELATED_IMAGE_CLIENT_SERVER: registry.redhat.io/rhtas/client-server-rhel9@sha256:58ed61e60fb8447fa9c9af4996efe612ed3220f291c9e190cfbb785df0585410
  RELATED_IMAGE_CTLOG: registry.redhat.io/rhtas/certificate-transparency-rhel9@sha256:3159240fc4f2e300a4b47462c62a77a939cef171f6eac5ec1e1093e34cf013be
  RELATED_IMAGE_FULCIO_SERVER: registry.redhat.io/rhtas/fulcio-rhel9@sha256:bce238dcadc51ce6a8780391c8fcfd829af1f83798869665840b179b5831d701
  RELATED_IMAGE_HTTP_SERVER: registry.access.redhat.com/ubi9/httpd-24@sha256:7874b82335a80269dcf99e5983c2330876f5fe8bdc33dc6aa4374958a2ffaaee
  RELATED_IMAGE_REKOR_REDIS: registry.redhat.io/rhtas/trillian-redis-rhel9@sha256:02b4b7af366c6cda6b0ae0a9559936b65141c4e866ec7953b46f24afb737a6a7
  RELATED_IMAGE_REKOR_SEARCH_UI: registry.redhat.io/rhtas/rekor-search-ui-rhel9@sha256:fecab83a8109b21f8000d0a6cfc32b93c7917c4cc9882fc2bcd291609af7a721
  RELATED_IMAGE_REKOR_SERVER: registry.redhat.io/rhtas/rekor-server-rhel9@sha256:c89aa7af31371e1eb2327fd4d734e6f8a02dde5ff77d1bd5a72f7ad823fb95bb
  RELATED_IMAGE_SEGMENT_REPORTING: registry.redhat.io/rhtas/segment-reporting-rhel9@sha256:c82f1662abd2be2b5f2670ec9471e92132f61787d72fb51b9eb9f57a4048498c
  RELATED_IMAGE_TIMESTAMP_AUTHORITY: registry.redhat.io/rhtas/timestamp-authority-rhel9@sha256:95c85f8ef635045bcf5b91d63a79fb7c0f9856ce18b58ffb062947dd6c8289e5
  RELATED_IMAGE_TRILLIAN_CREATE_TREE: registry.redhat.io/rhtas/createtree-rhel9@sha256:71b478f1e28df8e86e6f34a257de262ee3ad85d185a10095386471d24252f4ae
  RELATED_IMAGE_TRILLIAN_DB: registry.redhat.io/rhtas/trillian-database-rhel9@sha256:59d49f98f6da831aa6cf5f7d505ed356ac99e372de5c0140699cf0f0303a5b0a
  RELATED_IMAGE_TRILLIAN_LOG_SERVER: registry.redhat.io/rhtas/trillian-logserver-rhel9@sha256:2ba58ae1161e05088ce82e0d4a1a34603173e1e407abf968d2e86c5a19e3224f
  RELATED_IMAGE_TRILLIAN_LOG_SIGNER: registry.redhat.io/rhtas/trillian-logsigner-rhel9@sha256:e109c6665531a6678d667385391a4167c449704263aa1eff1ca7f98917054bc9
  RELATED_IMAGE_TRILLIAN_NETCAT: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:486b4d2dd0d10c5ef0212714c94334e04fe8a3d36cf619881986201a50f123c7
  RELATED_IMAGE_TUF: registry.redhat.io/rhtas/tuffer-rhel9@sha256:f809a7147af3caffb9dd7212c3dc327f5a5944e227fd590a2a659900f4b44b64
kind: ConfigMap
metadata:
  name: rhtas-related-images
