apiVersion: v1
data:
  RELATED_IMAGE_BACKFILL_REDIS: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9@sha256:631cebd3f08ccaba66a7a16f20f87af6c921810d1671a69e39c26dfd6f63d6f4
  RELATED_IMAGE_CLIENT_SERVER: registry.redhat.io/rhtas/client-server-rhel9@sha256:58ed61e60fb8447fa9c9af4996efe612ed3220f291c9e190cfbb785df0585410
  RELATED_IMAGE_CTLOG: registry.redhat.io/rhtas/certificate-transparency-rhel9@sha256:3159240fc4f2e300a4b47462c62a77a939cef171f6eac5ec1e1093e34cf013be
  RELATED_IMAGE_FULCIO_SERVER: registry.redhat.io/rhtas/fulcio-rhel9@sha256:e998c91223ae47e69486e6204f42b8d2f295c8bf9e2c6feea4c4b64918728d48
  RELATED_IMAGE_HTTP_SERVER: registry.access.redhat.com/ubi9/httpd-24@sha256:7874b82335a80269dcf99e5983c2330876f5fe8bdc33dc6aa4374958a2ffaaee
  RELATED_IMAGE_REKOR_REDIS: registry.redhat.io/rhtas/trillian-redis-rhel9@sha256:02b4b7af366c6cda6b0ae0a9559936b65141c4e866ec7953b46f24afb737a6a7
  RELATED_IMAGE_REKOR_SEARCH_UI: registry.redhat.io/rhtas/rekor-search-ui-rhel9@sha256:8be457b21855880581a36552e9ae9ace03770b9c1ec0264340d1baf2ebddbc7d
  RELATED_IMAGE_REKOR_SERVER: registry.redhat.io/rhtas/rekor-server-rhel9@sha256:cb1ac1f5e18376762a7974957500ce493fcde074eb4ef5b9f7b8e6e8738430df
  RELATED_IMAGE_SEGMENT_REPORTING: registry.redhat.io/rhtas/segment-reporting-rhel9@sha256:2c91fd97187e760a56999e2dea5973ffa32929d3bbdc81a3cbb1fe28b28149c3
  RELATED_IMAGE_TIMESTAMP_AUTHORITY: registry.redhat.io/rhtas/timestamp-authority-rhel9@sha256:95c85f8ef635045bcf5b91d63a79fb7c0f9856ce18b58ffb062947dd6c8289e5
  RELATED_IMAGE_TRILLIAN_CREATE_TREE: registry.redhat.io/rhtas/createtree-rhel9@sha256:777243778cc202d317b9350773b1faff33e99325b837b69e398f80e9479dae13
  RELATED_IMAGE_TRILLIAN_DB: registry.redhat.io/rhtas/trillian-database-rhel9@sha256:1457e4ecc16a9fb6d93994dddecba2bd5dd2c32974dbb55d97b610e8446e4110
  RELATED_IMAGE_TRILLIAN_LOG_SERVER: registry.redhat.io/rhtas/trillian-logserver-rhel9@sha256:9101809aa904530d51e592576707932e0da96a3be4d4ecc03f9bcabc0db8d7a6
  RELATED_IMAGE_TRILLIAN_LOG_SIGNER: registry.redhat.io/rhtas/trillian-logsigner-rhel9@sha256:c499438e52f4c6bf09dcb28761cbd1a1d08ca0c3c07f66c205e316f36bf54e2d
  RELATED_IMAGE_TRILLIAN_NETCAT: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:486b4d2dd0d10c5ef0212714c94334e04fe8a3d36cf619881986201a50f123c7
  RELATED_IMAGE_TUF: registry.redhat.io/rhtas/tuffer-rhel9@sha256:f809a7147af3caffb9dd7212c3dc327f5a5944e227fd590a2a659900f4b44b64
kind: ConfigMap
metadata:
  name: rhtas-related-images
