  operators.openshift.io/valid-subscription: '["Red Hat Trusted Artifact Signer"]'

  features.operators.openshift.io/disconnected: "false"
  features.operators.openshift.io/fips-compliant: "false"
  features.operators.openshift.io/proxy-aware: "true"
  features.operators.openshift.io/cnf: "false"
  features.operators.openshift.io/cni: "false"
  features.operators.openshift.io/csi: "false"
  features.operators.openshift.io/tls-profiles: "false"
  features.operators.openshift.io/token-auth-aws: "false"
  features.operators.openshift.io/token-auth-azure: "false"
  features.operators.openshift.io/token-auth-gcp: "false"
