apiVersion: v1
kind: Service
metadata:
  name: controller-manager-webhook-service
  namespace: system
  labels:
    control-plane: operator-controller-manager
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    control-plane: operator-controller-manager
