apiVersion: rhtas.redhat.com/v1alpha1
kind: CTlog
metadata:
  labels:
    app.kubernetes.io/name: securesign-sample
    app.kubernetes.io/instance: securesign-sample
    app.kubernetes.io/part-of: trusted-artifact-signer
  name: ctlog-sample
spec:
  # TODO(user): Add fields here
