apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgresql_db_secret.yaml
- postgresql_db_service.yaml
- postgresql_db.yaml
- keycloak.yaml
- keycloak_realm_import.yaml

namespace: keycloak-system

configMapGenerator:
  - name: base-hostname
    envs:
      - hostname.env

replacements:
  - source:
      kind: ConfigMap
      name: base-hostname
      version: v1
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Keycloak
          name: keycloak
        fieldPaths:
          - spec.hostname.hostname
