apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.securesigns.rhtas.redhat.com
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
