apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

patches:
  - path: serving_cert_annotation_patch.yaml
    target:
      kind: Service
      name: controller-manager-webhook-service

  - path: inject_ca_bundle_annotation_patch.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: validation.securesigns.rhtas.redhat.com
