apiVersion: v1
kind: Service
metadata:
  name: controller-manager-webhook-service
  namespace: openshift-rhtas-operator
  labels:
    control-plane: controller-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-tls
