apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: openshift-rhtas-operator
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-serving-cert
  namespace: openshift-rhtas-operator
spec:
  secretName: webhook-server-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
  - rhtas-controller-manager-webhook-service.openshift-rhtas-operator.svc
  - rhtas-controller-manager-webhook-service.openshift-rhtas-operator.svc.cluster.local
