apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak-system

resources:
  - ../../base
  - postgres.yaml

patches:
- path: keycloak_patch.yaml

configMapGenerator:
  - name: base-hostname
    envs:
      - hostname.env

replacements:
  - source:
      kind: ConfigMap
      name: base-hostname
      version: v1
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: Keycloak
          name: keycloak
        fieldPaths:
          - spec.hostname.hostname
